### ISSUE TITLE
Corregir nombre mal escrito en columna de Contract

### ISSUE THREAD

**Issue by Nanito111** [Nanito111/CAPSTONE_002D#157]
La columna `electricityCost` esta mal escrita en la tabla **Contract**
![Image](https://github.com/user-attachments/assets/9f6631dd-f556-4f70-a114-04d39848b20e)
Esta escrito como `elecricityCost`. Le falta la **T** despues de _elec_

### TODO
- [x] modificar DLL (no es necesario generar uno nuevo, solo cambiar el nombre de la columna en el existente)
- [x] generar nuevos diagramas
- [x] modificar nombre de columna en la BD
